### PR TITLE
Swap "/works/" for "/items/".

### PR DESCRIPTION
**Pull request by mathewjordan**
This swaps out out the directory from `works` to `items` to retain SEO value.

### CODE REVIEW

**Review by kdid — APPROVED** [review]
Screen Shot 2022-08-18 at 8 58 46 AM


@mathewjordan - Approving. There is a reference in the readme if you want to fix it.

**Comment by mathewjordan** [comment]
Thanks @kdid I'll adjust readme as well.

**Comment by mathewjordan** [comment]
Err, wait. Looks like that reference is for the API. That's a different thing altogether.

**Comment by kdid** [comment]
Oh cool, sorry!

**Pull request merged**
