### PR TITLE
Add placeholder texts to AI search

### PR DESCRIPTION
**Pull request by adamjarling**
## What does this do?
- Changes Search `input` element to `textarea` element
- `textarea` placeholder text changes based on whether AI chat is engaged
- Put in some language on AI results when no prompt has been entered

image

@davidschober @vlsrobinson @mathewjordan  Let me know about the placeholder text?

## How to test
- Verify placeholder texts
- Try copying or writing a lot of text into the search input to validate its a `textarea` and will wrap vertically.

### CODE REVIEW

**Review by mathewjordan — APPROVED** [review]
I like it. For the textarea, I think we need one more issue to flesh it out UX. 

- Detect textarea scrollHeight to auto grow the height of the area, so that as the user types and the textarea is in focus
- When user unfocuses, peel back height to minheight and add `...` text overflow to indicate a long wrapping string
- Remove fixed height of the header to allow for fluid growth by use of minheight where height has been set
- Refine form buttons so that they don't grow in height as well
- Test for fixed height
- Test responsively

**Comment by mathewjordan** [comment]
Created https://github.com/nulib/repodev_planning_and_docs/issues/5045

**Comment by vlsrobinson** [comment]
Should we prompt the user to ask a question, instead of 'try searching for..' maybe something like "try asking a question like, who are some musicians who played at the Berkeley Folk Music Festival?"

**Comment by adamjarling** [comment]
> Should we prompt the user to ask a question, instead of 'try searching for..' maybe something like "try asking a question like, who are some musicians who played at the Berkeley Folk Music Festival?"

Sure that sounds like a good idea @vlsrobinson .  One UI consideration (now that this is a `textarea` element, is that the placeholder text needs to fit on one line, and avoid spilling onto a second line.  Roughly ~55 characters of space available.

**Comment by adamjarling** [comment]
@vlsrobinson Because there are some new UI considerations to code for, I'm going to merge this now, and then we can flesh out the text at anytime.

**Pull request merged**
